In [132]:
import pandas as pd
import numpy as np

import plotly.express as px
from sklearn.linear_model import LogisticRegression
from plotly.graph_objects import *
from plotly.offline import init_notebook_mode,iplot
init_notebook_mode(connected=True)

In [133]:
df = pd.read_csv('diabetes2.csv')

In [134]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI   
0            6      148             72             35        0  33.6  \
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [135]:
df.isnull().sum() #NULL

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [136]:
df.select_dtypes(np.number).columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [137]:
corr=df.corr()

In [138]:
corr[((corr>0.7)|(corr<-0.7)) & (corr != 1)] #Вискої кореляції немає

Pregnancies  Glucose  BloodPressure  SkinThickness   
Pregnancies                       NaN      NaN            NaN            NaN  \
Glucose                           NaN      NaN            NaN            NaN   
BloodPressure                     NaN      NaN            NaN            NaN   
SkinThickness                     NaN      NaN            NaN            NaN   
Insulin                           NaN      NaN            NaN            NaN   
BMI                               NaN      NaN            NaN            NaN   
DiabetesPedigreeFunction          NaN      NaN            NaN            NaN   
Age                               NaN      NaN            NaN            NaN   
Outcome                           NaN      NaN            NaN            NaN   

                          Insulin  BMI  DiabetesPedigreeFunction  Age  Outcome  
Pregnancies                   NaN  NaN                       NaN  NaN      NaN  
Glucose                       NaN  NaN                       NaN  NaN      NaN  
BloodPressure                 NaN  NaN                       NaN  NaN      NaN  
SkinThickness                 NaN  NaN                       NaN  NaN      NaN  
Insulin                       NaN  NaN                       NaN  NaN      NaN  
BMI                           NaN  NaN                       NaN  NaN      NaN  
DiabetesPedigreeFunction      NaN  NaN                       NaN  NaN      NaN  
Age                           NaN  NaN                       NaN  NaN      NaN  
Outcome                       NaN  NaN                       NaN  NaN      NaN

In [139]:
x = df[df.columns.drop(['Outcome'])] #видаляємо тільки outcome
y = df['Outcome']

In [140]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                                   test_size=0.2)

In [141]:
x_train.describe() 

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin   
count   614.000000  614.000000     614.000000     614.000000  614.000000  \
mean      3.944625  120.848534      69.060261      20.288274   80.513029   
std       3.398521   32.183074      19.212844      15.846942  117.330249   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      22.500000   36.000000   
75%       6.000000  140.000000      80.000000      32.000000  126.000000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age  
count  614.000000                614.000000  614.000000  
mean    31.809609                  0.470958   33.480456  
std      8.059604                  0.326242   12.136342  
min      0.000000                  0.078000   21.000000  
25%     26.925000                  0.238000   24.000000  
50%     32.000000                  0.380000   29.000000  
75%     36.400000                  0.628500   41.000000  
max     67.100000                  2.420000   81.000000

In [142]:
#LogisticRegression()
mod = LogisticRegression()
mod.fit(x_train,y_train)

C:\Users\Dinamicka Laptop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression



LogisticRegression()

In [143]:
mod.coef_,mod.intercept_

(array([[ 1.17940796e-01,  3.32901874e-02, -9.80829705e-03,
         -4.99858334e-03, -2.91606043e-04,  7.95762352e-02,
          1.64956101e+00,  1.52048891e-02]]),
 array([-8.46333355]))

In [144]:
preds = mod.predict(x_test)
preds

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0],
      dtype=int64)

In [145]:
#ймовірності p
predict_prob=mod.predict_proba(x_test)
predict_prob[0]

array([0.8846363, 0.1153637])

In [146]:
#функція сігмоїда
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [147]:
#заносимо дані у таблицю, 
df_1=pd.DataFrame(x_test)
df_1['y']=pd.DataFrame(y_test)
df_1['pred_cl']=mod.predict(x_test) #наше передбачення
df_1['pred_prob']=sigmoid(x_test.dot(mod.coef_.T)+mod.intercept_) #передбачення ймовірності <0,5-група 0; >0,5-група 1

df_1.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI   
321            3      112             74             30        0  31.6  \
578           10      133             68              0        0  27.0   
670            6      165             68             26      168  33.6   
100            1      163             72              0        0  39.0   
184            4      141             74              0        0  27.6   

     DiabetesPedigreeFunction  Age  y  pred_cl  pred_prob  
321                     0.197   25  1        0   0.115364  
578                     0.245   36  0        0   0.395747  
670                     0.631   49  0        1   0.794285  
100                     1.222   33  1        1   0.880346  
184                     0.244   40  0        0   0.306512

In [148]:
#метрика
(df_1['y'] == df_1['pred_cl']).mean()

0.7272727272727273

In [149]:
#метрика 
mod.score(x_test, y_test)

0.7272727272727273

---Confusion_matrix

In [168]:
from sklearn.metrics import confusion_matrix

In [174]:
a=confusion_matrix(df_1['y'],df_1['pred_cl'])
a
#TP(TT)-83, FP(FT)-8, FN(TF)-34, TN(FF)-30

array([[82,  8],
       [34, 30]], dtype=int64)

In [171]:
df_1.count() #перевірка по суммі

Pregnancies                 154
Glucose                     154
BloodPressure               154
SkinThickness               154
Insulin                     154
BMI                         154
DiabetesPedigreeFunction    154
Age                         154
y                           154
pred_cl                     154
pred_prob                   154
dtype: int64

In [218]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

presicion

In [193]:
presicion=a[0,0]/sum(a[0,:]) #presicion
presicion

0.9111111111111111

In [207]:
precision_score(df_1['y'],df_1['pred_cl'],average='micro')

0.7272727272727273

In [208]:
precision_score(df_1['y'],df_1['pred_cl'],average='macro')

0.7481851179673321

In [209]:
precision_score(df_1['y'],df_1['pred_cl'],average='weighted')

0.7412143210691305

Recall

In [183]:
recall=a[0,0]/sum(a[:,0]) #recall
recall

0.7068965517241379

In [211]:
recall_score(df_1['y'],df_1['pred_cl'], average='macro')

0.6899305555555555

In [212]:
recall_score(df_1['y'],df_1['pred_cl'], average='micro')

0.7272727272727273

In [213]:
recall_score(df_1['y'],df_1['pred_cl'],  average='weighted')

0.7272727272727273

f1

In [202]:
f1=(2*presicion*recall)/(recall+presicion) #f1
f1

0.7961165048543689

In [221]:
f1_score(df_1['y'],df_1['pred_cl'], average='macro')

0.692175899486008

In [222]:
f1_score(df_1['y'],df_1['pred_cl'], average='micro')

0.7272727272727273

In [223]:
f1_score(df_1['y'],df_1['pred_cl'], average='weighted')

0.7097243133793677

ROC AUC

In [205]:
roc_auc_score(df_1['y'],df_1['pred_prob'])

0.795138888888889

Кросс валідація через sklearn 
https://medium.datadriveninvestor.com/a-comprehensive-analysis-of-pima-indians-diabetes-f5cf9f73 (для себе)

In [150]:
from sklearn.model_selection import cross_validate
def base_models(X, y, scoring="roc_auc"):
    classifiers = [('LR', LogisticRegression())]

    for name, classifier in classifiers:
        cv_results = cross_validate(classifier, X, y, cv=3, scoring=scoring)
        print(f"{scoring}: {round(cv_results['test_score'].mean(), 4)} ({name}) ")

In [167]:
base_models(x_train, y_train, scoring='accuracy') 

accuracy: 0.7916 (LR) 


C:\Users\Dinamicka Laptop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

C:\Users\Dinamicka Laptop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

C:\Users\Dinamicka L

In [152]:
base_models(x_test, y_test, scoring='accuracy') 

accuracy: 0.7342 (LR) 


C:\Users\Dinamicka Laptop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

C:\Users\Dinamicka Laptop\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

C:\Users\Dinamicka L